# 25940 | Starting Script

sm.setSpeakerID(9000185)
sm.sendNext("You're going to be a #r#eMaple Chat#k#n devotee, just like me!")
sm.sendSay("#i3800484# Maple Chat isn't so new, ya know? It's basically just a fancy #b#enew version#k#n of the #b#ecurrent messenger#k#n! You can still use the #r#esame hotkey#k#n or just come talk to me!\n\n")
sm.sendSay("#i3800485# This is what you'll see when you #b#efirst#k#n open Maple Chat. Looks pretty friendly, huh?\n")
sm.sendSay("#i3800486# Do you know what #b#ethis#k#n is? This is where you can check out your #r#eLikability#k#n!\n")
sm.sendSay("You can #b#eexchange Likability points during any random chat#k#n. You can only give #r#eone point to each person per day#k#n, up to #r#e10 times total#k#n. #i3800487#")
sm.sendSay("Your Likability points reset #r#eevery Monday at midnight#k#n. The guy and the gal with the #b#emost Likability points#k#n will be displayed in the Hall of Honor here! Isn't that cool?#i3800488#. \n")
sm.sendSay("Pretty crazy right? If you want to be on that board, you have to #r#etreat others with respect#k#n and be #r#eentertaining#k#n. Make it snappy, that's what Eileen says!\n")
sm.sendSay("There are #b#ethree ways#k#n to get into your chat: #i3800489##r#ePrivate Chat, Group Chat, and Friend Chat#k#n!")
sm.sendSay("Private and Group chats are #r#erandomnized#k#n. You never know who you'll end up talking to! ")
sm.sendSay("#i03800490# Choose #r#ePrivate Chat#k#n for #b#epersonal conversations#k#n and #r#eGroup Chat#k#n for #b#eexciting community chats#k#n. Simple, right?")
sm.sendSay("#i3800491# Chatting with your friends should feel pretty much the same. You can still talk to #b#eanyone and invite friends#k#n to chat. It's a great way to get to know others.\n")
sm.sendSay("Did you get all that?\r\nWelp, that was my #b#esimple explanation of Maple Chat#k#n.\r\n#r#eCome talk to me any time#n#k \r\nif you have more questions!")
sm.sendSayOkay("Oh, and #b#ehere's a little gift for you.#k#n\r\nBefore you go, talk to me #r#ein town#n#k!\r\n")
