# 4942 | Starting Script

sm.setSpeakerID(9201079)
sm.sendNext("Thank you. Thank you so much.\r\nForgive my rough words earlier. My name is Thomlin Prendergast. Jonas was my older brother. The story I told you before was true... I was there. After Sophilia's accident, Jonas went mad. He locked himself in his workshop, refusing to see anyone, ignoring our pleas through the door to take food and water. Even the constant thrum of the Prendergast Toy Machine that once permeated the house fell silent as Jonas mourned.")
sm.sendSay("One day, the noises of the Toy Machine started up again! We rushed up to the Workshop door, hoping that Jonas had come out. But the door remained locked, and the noises coming from within... these were not the same noises as before! It was a terrible screeching, like the grinding of gears, fearsome thumping noises, and god knows what else!")
sm.sendSay("To make matters worse, many of the household staff swore to have seen the ghost of Sophilia... and they began to desert the house. I confess... I saw her myself. Soon, everyone had left. The only ones who remained behind were me, Edmunds, our loyal butler, and Jonas' wife, Ludmilla, who could not bear to leave the life she had to which she had grown accustomed.")
sm.sendSay("I had an extra key to Jonas' Workshop, and Edmunds begged me to go in and talk to my brother. With great fear and trepidation, I ascended to the top of the house, climbing to the heights of my brother's workspace.")
sm.sendSay("There, I found Jonas... dead at the controls of his Toy Machine. He had been dead for awhile. There were toys everywhere.")
sm.sendSay("Standing there, in front of my brother's lifeless body, his huge mechanical contraption looming above me... I couldn't help but feel that somehow part of Jonas' spirit, his grief, had entered his Toy Machine. As if it had heard my thoughts, the machine began to crank out toys... monstrous toys I had never seen before! They were my brother's toys... but twisted, hateful. In my haste and fright, I dropped my key as I fled the house.  I... I have never gone back in since.")
sm.sendSayOkay("... I realize now what my mission is. Please talk to me in a minute.")
