package net.swordie.ms.enums;

/**
 * Created on 1/25/2018.
 */
public enum MessageType {
    DROP_PICKUP_MESSAGE(0),
    QUEST_RECORD_MESSAGE(1),
    QUEST_RECORD_MESSAGE_ADD_VALID_CHECK(2),
    CASH_ITEM_EXPIRE_MESSAGE(3),
    INC_EXP_MESSAGE(4),
    INC_SP_MESSAGE(5),
    INC_POP_MESSAGE(6),
    INC_MONEY_MESSAGE(7),
    INC_GP_MESSAGE(8),
    INC_COMMITMENT_MESSAGE(9),
    GIVE_BUFF_MESSAGE(10),
    GENERAL_ITEM_EXPIRE_MESSAGE(11),
    SYSTEM_MESSAGE(12),
    QUEST_RECORD_EX_MESSAGE(13),
    WORLD_SHARE_RECORD_MESSAGE(14),
    ITEM_PROTECT_EXPIRE_MESSAGE(15),
    ITEM_EXPIRE_REPLACE_MESSAGE(16),
    ITEM_ABILITY_TIME_LIMITED_EXPIRE_MESSAGE(17),
    SKILL_EXPIRE_MESSAGE(18),
    INC_NON_COMBAT_STAT_EXP_MESSAGE(19),
    LIMIT_NON_COMBAT_STAT_EXP_MESSAGE(20),
    ANDROID_MACHINE_HEART_ALSET_MESSAGE(22),
    INC_FATIGUE_BY_REST_MESSAGE(23),
    INC_PVP_POINT_MESSAGE(24),
    PVP_ITEM_USE_MESSAGE(25),
    WEDDING_PORTAL_ERROR(26),
    INC_HARDCORE_EXP_MESSAGE(27),
    NOTICE_AUTO_LINE_CHANGED(28),
    ENTRY_RECORD_MESSAGE(29),
    EVOLVING_SYSTEM_MESSAGE(30),
    EVOLVING_SYSTEM_MESSAGE_WITH_NAME(31),
    CORE_INVEN_OPERATION_MESSAGE(32),
    NX_RECORD_MESSAGE(33),
    BLOCKED_BEHAVIOR_MESSAGE(34),
    INC_WP_MESSAGE(35),
    MAX_WP_MESSAGE(36),
    STYLISH_KILL_MESSAGE(37),
    BARRIER_EFFECT_IGNORE_MESSAGE(38),
    EXPIRED_CASH_ITEM_RESULT_MESSAGE(39),
    COLLECTION_RECORD_MESSAGE(40),
    RANDOM_CHANCE_MESSAGE(41),
    UNK(42),

    ;

    private byte val;

    MessageType(int val) {
        this.val = (byte) val;
    }

    public byte getVal() {
        return val;
    }
}
